name: Integration Test

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Integration Test
      run: |
        sudo apt update
        sudo apt install device-tree-compiler
        dtc --version
        cargo build --release
        ./test/integration.sh